apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: keycloak
  name: keycloak-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


